definitions:
  main.Service:
    properties:
      cost:
        type: string
      currency:
        type: string
      duration:
        type: integer
      id:
        type: integer
      key_method:
        type: string
      name:
        type: string
      url:
        type: string
    type: object
  main.ServiceNoID:
    properties:
      cost:
        type: string
      currency:
        type: string
      duration:
        type: integer
      key_method:
        type: string
      name:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /addService:
    post:
      parameters:
      - description: Body parameter
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/main.ServiceNoID'
      responses:
        "200":
          description: ""
  /checkService:
    get:
      parameters:
      - description: Service name
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: 'Example \n {"result": true"}'
          schema:
            additionalProperties: true
            type: object
  /getServiceInfo:
    get:
      parameters:
      - description: Service name
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Service'
  /getServiceList:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Service'
            type: array
swagger: "2.0"
